# This is an Ansible (http://www.ansibleworks.com/) playbook that will
# configure a host as an OpenVPN gateway for a network specified by
# remote_network_addr and remote_network_mask.  It will configure the host
# identified as vpngw-local as a client of the remote VPN instance, with
# appropriate routes configured to reach the remote network.
#
# The use case behind this playbook is using OpenVPN as the VPN gateway
# to instances running in an Amazon VPC.  This requires appropriately 
# configuring the routing in your VPC environment.

- hosts: vpngw-aws
  user: fedora
  sudo: true
  vars:
  - remote_network_addr: 10.243.16.192
  - remote_network_mask: 255.255.255.224
  - remote_ptp_addr: 172.16.33.10
  - local_ptp_addr: 172.16.33.1
  tasks:

  # Install a required packages.
  - yum: name=$item state=installed
    with_items:
    - openvpn
    - selinux-policy-devel

  # Generate local and remote OpenVPN configuration files.
  - template: src=vpcgw-local.conf dest=/etc/openvpn/vpcgw.conf
    delegate_to: vpngw-local
    notify: restart local openvpn
  - template: src=vpcgw-aws.conf dest=/etc/openvpn/vpcgw.conf owner=root group=root mode=0644
    notify:
    - restart openvpn

  # Install the shared secret.  Note that this is not part of the repository; you
  # will need to generate it manually by running:
  # openvpn --genkey --secret vpcgw.key
  - copy: src=vpcgw.key dest=/etc/openvpn/vpcgw.key owner=root group=root mode=0400
    notify:
    - restart openvpn

  # This muck is necessary because the selinux policy in Fedora 19
  # does not have all the necessary permissions for OpenVPN to operate
  # with selinux in enforcing mode.
  - file: path=/etc/selinux/local state=directory
  - copy: src=$item dest=/etc/selinux/local/
    with_items:
    - selinux/Makefile
    - selinux/local_tuntap.te
    - selinux/local_openvpn.te
    notify:
    - rebuild selinux modules

  #  Permit ip forwarding
  - copy: src=ip_forward.conf dest=/etc/sysctl.d/ip_forward.conf
    notify:
    - restart sysctl
  - copy: src=iptables dest=/etc/sysconfig/iptables
    notify:
    - restart iptables

  # Make sure openvpn is enabled.
  - service: name=openvpn@vpcgw state=running enabled=true
  handlers:
  - name: rebuild selinux modules
    command: make -C /etc/selinux/local install
  - name: restart sysctl
    command: /bin/systemctl restart systemd-sysctl
  - name: restart openvpn
    command: /bin/systemctl restart openvpn@vpcgw
  - name: restart iptables
    command: /bin/systemctl restart iptables
  - name: restart local openvpn
    service: name=openvpn@vpcgw state=restarted
    delegate_to: vpngw_local

# The OpenVPN configuration is generated in the previous play,
# but we still need to install the shared secret.
- hosts: vpngw-local
  sudo: true
  tasks:
  - copy: src=vpcgw.key dest=/etc/openvpn/vpcgw.key owner=root group=root mode=0400
    notify:
    - restart openvpn
  handlers:
  - name: restart openvpn
    command: /bin/systemctl restart openvpn@vpcgw

