- hosts: vpngw
  user: fedora
  sudo: true
  tasks:
  - yum: name=$item state=installed
    with_items:
    - openvpn
    - nmap
    - bridge-utils
    - system-config-firewall-base
    - selinux-policy-devel
  - file: path=/etc/selinux/local state=directory
  - copy: src=$item dest=/etc/selinux/local/
    with_items:
    - selinux/Makefile
    - selinux/local_tuntap.te
    - selinux/local_openvpn.te
    notify:
    - rebuild selinux modules
  - copy: src=vpcgw.conf dest=/etc/openvpn/vpcgw.conf owner=root group=root mode=0644
  - copy: src=vpcgw.key dest=/etc/openvpn/vpcgw.key owner=root group=root mode=0400
  - copy: src=ip_forward.conf dest=/etc/sysctl.d/ip_forward.conf
    notify:
    - reload sysctl
  - command: /usr/sbin/lokkit -s ssh -s openvpn --update
  - service: name=openvpn@vpcgw state=running enabled=true
  handlers:
  - name: rebuild selinux modules
    command: make -C /etc/selinux/local install
  - name: reload sysctl
    command: /bin/systemctl restart systemd-sysctl
 
